name: "Proxy test"
description: "Tests using a proxy specified by the https_proxy environment variable"
versions: ["latest"]
operatingSystems: ["ubuntu"]
container:
  image: ubuntu:22.04
  options: --dns 127.0.0.1
services:
  squid-proxy:
    image: ubuntu/squid:latest
    ports:
      - 3128:3128
env:
  https_proxy: http://squid-proxy:3128
steps:
  - uses: ./../action/init
    with:
      languages: javascript
      tools: ${{ steps.prepare-test.outputs.tools-url }}
      token: ${{ secrets.CODEQL_TOKEN }}
  - uses: ./../action/analyze
    with:
      upload-database: false
      token: ${{ secrets.CODEQL_TOKEN }}
